backend:
  name: github
  repo: jmcinern/Lenihan-Landscaping-Frontend
  branch: main

media_folder: "y/public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      # Homepage
      - label: "Home Page"
        name: "home"
        file: "y/src/data/home.json"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "USP Text", name: "usp", widget: "string" }
          - { label: "Button Text", name: "button_text", widget: "string" }
      
      # About Page
      - label: "About Page"
        name: "about"
        file: "y/src/data/about.json"
        fields:
          - { label: "Our Story", name: "story", widget: "markdown" }
          - { label: "The Team", name: "team", widget: "markdown" }
          - { label: "Qualifications", name: "qualifications", widget: "string" }
          - label: "Our Values"
            name: "values"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "string" }

      # Services Page
      - label: "Services Page"
        name: "services"
        file: "y/src/data/services.json"
        fields:
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }

      # Contact Page
      - label: "Contact Page"
        name: "contact"
        file: "y/src/data/contact.json"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Service Area", name: "area", widget: "string" }

  # Portfolio Collection
  - name: "portfolio"
    label: "Portfolio"
    folder: "y/src/content/portfolio"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Hero Image", name: "heroImage", widget: "image", optional: true }
      - { label: "Body", name: "body", widget: "markdown" }